# Dados de exemplo
Conselhos = [
  {"slip":{"id": 1, "conselho": "Seja gentil consigo mesmo, você merece."}},
  {"slip":{"id": 2, "conselho": "Acredite no seu potencial, você é mais capaz do que imagina."}},
  {"slip":{"id": 3, "conselho": "Celebre suas pequenas conquistas, elas são importantes."}},
  {"slip":{"id": 4, "conselho": "Lembre-se de respirar fundo quando estiver estressado."}},
  {"slip":{"id": 5, "conselho": "Aprenda com seus erros, eles são oportunidades de crescimento."}},
  {"slip":{"id": 6, "conselho": "Cultive relacionamentos significativos, eles são essenciais para o bem-estar."}},
  {"slip":{"id": 7, "conselho": "Pratique a gratidão diariamente, isso traz felicidade."}},
  {"slip":{"id": 8, "conselho": "Saia da sua zona de conforto de vez em quando, é onde a magia acontece."}},
  {"slip":{"id": 9, "conselho": "Seja paciente consigo mesmo, o progresso leva tempo."}},
  {"slip":{"id": 10, "conselho": "Não se compare aos outros, cada jornada é única."}},
  {"slip":{"id": 11, "conselho": "Aproveite o momento presente, é tudo o que realmente temos."}},
  {"slip":{"id": 12, "conselho": "Faça pausas regulares para descansar e recarregar suas energias."}},
  {"slip":{"id": 13, "conselho": "Pratique a empatia, coloque-se no lugar dos outros."}},
  {"slip":{"id": 14, "conselho": "Encontre tempo para fazer o que você ama, isso alimenta sua alma."}},
  {"slip":{"id": 15, "conselho": "Mantenha uma mente aberta e flexível, isso permite o crescimento."}},
  {"slip":{"id": 16, "conselho": "Defina metas alcançáveis ​​e trabalhe consistentemente para alcançá-las."}},
  {"slip":{"id": 17, "conselho": "Dê-se permissão para dizer não quando necessário, sua saúde mental é importante."}},
  {"slip":{"id": 18, "conselho": "Aprenda a perdoar, isso libera você do peso do ressentimento."}},
  {"slip":{"id": 19, "conselho": "Seja corajoso o suficiente para seguir o que seu coração deseja."}},
  {"slip":{"id": 20, "conselho": "Valorize-se e reconheça sua própria grandeza."}},
  {"slip":{"id": 21, "conselho": "Aproveite os momentos simples da vida, eles são os mais preciosos."}},
  {"slip":{"id": 22, "conselho": "Pratique a autocompaixão, trate-se com bondade e compreensão."}},
  {"slip":{"id": 23, "conselho": "Acredite na beleza dos seus sonhos e trabalhe para realizá-los."}},
  {"slip":{"id": 24, "conselho": "Mantenha uma atitude positiva, ela atrai coisas boas para sua vida."}},
  {"slip":{"id": 25, "conselho": "Crie uma rotina de autocuidado, sua saúde física e mental são preciosas."}},
  {"slip":{"id": 26, "conselho": "Seja grato pelas lições que a vida lhe ensina, elas o tornam mais forte."}},
  {"slip":{"id": 27, "conselho": "Ame-se incondicionalmente, você é único e especial."}},
  {"slip":{"id": 28, "conselho": "Aprenda a dizer sim para as oportunidades que o levam a crescer."}},
  {"slip":{"id": 29, "conselho": "Acredite na sua capacidade de superar desafios, você é resiliente."}},
  {"slip":{"id": 30, "conselho": "Nunca desista dos seus sonhos, o sucesso pode estar ao virar da esquina."}},
] 